### ISSUE TITLE
Avoid functions with lots of parameters

### ISSUE THREAD

**Issue by thiagooak** [abarretti/SantaMonicaMovieRentalsSILEX#1]
https://github.com/abarretti/SantaMonicaMovieRentalsSILEX/blob/fe851806f7a8c264c8dc044a22669255cbdba11e/index.php#L57

- You should not use the DAO here, the DAO should only be accessed from the Model
- You could have a method `getAllGeneres` that requires less params and since you are moving it to the Model you don't really need to pass them as params as they will be on the same object

**Comment by abarretti** [comment]
I'm going to focus on this next. All DAO functions in the index.php file will now be called via their respective models. I will also change the functions to accept a single array parameter rather than many individual parameters.

**Comment by abarretti** [comment]
Just finished this. There is probably additional functions within the models that I could clean up too. But at least now I am not calling to the DAO object directly from the index file. It is done via the model with no parameters being passed since they are part of the object themselves.
