### ISSUE TITLE
DAO Namespace

### ISSUE THREAD

**Issue by thiagooak** [abarretti/SantaMonicaMovieRentalsSILEX#2]
https://github.com/abarretti/SantaMonicaMovieRentalsSILEX/blob/fe851806f7a8c264c8dc044a22669255cbdba11e/app/SMMRSite/Models/InventoryModels/inventoryDAOClass.php#L6

Please create a new namespace just for DAOs (like you did for Models and controllers) so the path for this class would be something like `/SMMRSite/DAOs/Inventory/InventoryDAO.php` or `/SMMRSite/DAOs/InventoryDAO.php`

**Comment by abarretti** [comment]
Done. I'll include it in my next pull request.
