### ISSUE TITLE
Use PDO instead of mysqli

### ISSUE THREAD

**Issue by thiagooak** [abarretti/SantaMonicaMovieRentalsSILEX#3]
https://github.com/abarretti/SantaMonicaMovieRentalsSILEX/blob/fe851806f7a8c264c8dc044a22669255cbdba11e/app/SMMRSite/Models/InventoryModels/inventoryDAOClass.php#L19

Or use the Doctrine DBAL https://silex.symfony.com/doc/2.0/providers/doctrine.html

**Comment by abarretti** [comment]
Just converted all the DAO's. It'll be in my next pull request.
