### ISSUE TITLE
Reference to missing Class

### ISSUE THREAD

**Issue by thiagooak** [abarretti/SantaMonicaMovieRentalsSILEX#5]
https://github.com/abarretti/SantaMonicaMovieRentalsSILEX/blob/fe851806f7a8c264c8dc044a22669255cbdba11e/app/SMMRSite/Models/InventoryModels/inventoryDAOClass.php#L3

`DAOClass` is not defined anywhere

**Comment by abarretti** [comment]
Should I just do "use SMMRSite\Models\DAOClass"? The inventoryDAOClass inherits from the DAOClass, so the file containing the DAOClass is required. Let me try running it and I'll know ;-)

**Comment by abarretti** [comment]
It worked. Closing this one out.
