### ISSUE TITLE
Centralize connection creation

### ISSUE THREAD

**Issue by thiagooak** [abarretti/SantaMonicaMovieRentalsSILEX#6]
https://github.com/abarretti/SantaMonicaMovieRentalsSILEX/blob/fe851806f7a8c264c8dc044a22669255cbdba11e/app/SMMRSite/Models/CustomerModels/customerDAOClass.php#L18

You are creating connections on your 3 DAOs. You can avoid code repetition by centralizing it (maybe in the DAOClass? would suggest the name BaseDAO instead)

**Comment by abarretti** [comment]
The connection is now initiated through a function in the BaseDAO which then stores the PDO object as a variable of the BaseDAO class. The PDO connection and close are now called in each of the 3 DAO's via the BaseDAO function so that the code isn't replicated every time.
