### ISSUE TITLE
Protect against SQL Injection

### ISSUE THREAD

**Issue by thiagooak** [abarretti/SantaMonicaMovieRentalsSILEX#7]
https://github.com/abarretti/SantaMonicaMovieRentalsSILEX/blob/fe851806f7a8c264c8dc044a22669255cbdba11e/app/SMMRSite/Models/InventoryModels/inventoryDAOClass.php#L121

See http://php.net/manual/en/mysqli.real-escape-string.php

**Comment by abarretti** [comment]
I am now using the PDO prepare and execute functions when using SQL INSERT INTO or UPDATE scripts in the DAOs. Should I go a step further and also use prepare/execute for all SELECT scripts?
